/**
 * The shipped registers.
 *
 * `parchment` is the proof the engine can hit a known-good target: its axes
 * resolve to roughly the Compose light values (warm off-white surface, off-black
 * ink, oxblood signal, teal link) without any hex being copied in.
 * `substrate` is the dark point in the same axis family; `print` is high
 * contrast on paper white. `console-dark` is the application-host register:
 * WCAG AA solved on a cool dark ground for pane-width reading inside a console
 * or IDE-adjacent host. It ships in two face variants (serif body, sans body
 * with serif display); see `CONSOLE_DARK_VARIANTS`.
 *
 * The console bridge points: a host embedding `console-dark` maps its own
 * planes onto exactly three emitted tokens -- `--gy-surface` (the reading
 * plane), `--gy-ground` (the canvas behind it), and `--gy-font-mono` (the code
 * face shared with the host terminal). Everything else stays internal to the
 * register. These three are the official contract; the pinned CSS artifacts in
 * `fixtures/css/` (regenerated by `pnpm emit:fixtures`) declare them.
 */

import { generateRegister, SERIF_PROSE } from "./register.js";
import type { Axes, Register } from "./types.js";
import { RATIOS } from "./types.js";

export const PARCHMENT_AXES: Axes = {
  base: 17,
  ratio: RATIOS.minorThird,
  measure: 68,
  hue: 74,
  chroma: 0.008,
  signalHue: 24,
  signalChroma: 0.12,
  linkHue: 218,
  linkChroma: 0.06,
  mode: "light",
  density: "reading",
};

export const SUBSTRATE_AXES: Axes = {
  base: 17,
  ratio: RATIOS.minorThird,
  measure: 68,
  hue: 72,
  chroma: 0.006,
  signalHue: 26,
  signalChroma: 0.11,
  linkHue: 216,
  linkChroma: 0.07,
  mode: "dark",
  density: "reading",
};

export const PRINT_AXES: Axes = {
  base: 11,
  ratio: RATIOS.majorThird,
  measure: 66,
  hue: 74,
  chroma: 0.003,
  signalHue: 24,
  signalChroma: 0.13,
  linkHue: 218,
  linkChroma: 0.05,
  mode: "print",
  density: "reading",
};

/**
 * The console register axes (the pinned seed for the `console-dark` artifacts).
 * A cool graphite ground (against substrate's warm dark), a slightly smaller
 * app base size, and a wider pane measure for 60-90ch application hosts. The
 * accent family stays with the house: warm signal, teal link.
 */
export const CONSOLE_DARK_AXES: Axes = {
  base: 16,
  ratio: RATIOS.minorThird,
  measure: 72,
  hue: 250,
  chroma: 0.008,
  signalHue: 26,
  signalChroma: 0.11,
  linkHue: 216,
  linkChroma: 0.08,
  mode: "dark",
  density: "reading",
};

/** A named fixture: axes plus the face choices layered on top. */
export interface FixtureVariant {
  axes: Axes;
  fonts?: Partial<Register["fonts"]>;
}

/**
 * The M4 face decision, made here: two variants over the same solved palette.
 * `console-dark-serif` is the publication register as shipped (Vollkorn body on
 * the dark ground); `console-dark-sans` is the denser IDE-adjacent register
 * (sans body, serif display). A consumer picks one by fixture name and can
 * reverse the decision by changing the name; both are generated and both pass
 * the same contrast gate (the palette is identical, faces never affect it).
 */
export const CONSOLE_DARK_VARIANTS = {
  "console-dark-serif": {
    axes: CONSOLE_DARK_AXES,
    fonts: { prose: SERIF_PROSE },
  },
  "console-dark-sans": {
    axes: CONSOLE_DARK_AXES,
    fonts: { title: SERIF_PROSE },
  },
} as const satisfies Record<string, FixtureVariant>;

export const parchment = () => generateRegister(PARCHMENT_AXES);
export const substrate = () => generateRegister(SUBSTRATE_AXES);
export const print = () => generateRegister(PRINT_AXES);
export const consoleDarkSerif = (): Register =>
  generateRegister(CONSOLE_DARK_VARIANTS["console-dark-serif"].axes, {
    fonts: CONSOLE_DARK_VARIANTS["console-dark-serif"].fonts,
  });
export const consoleDarkSans = (): Register =>
  generateRegister(CONSOLE_DARK_VARIANTS["console-dark-sans"].axes, {
    fonts: CONSOLE_DARK_VARIANTS["console-dark-sans"].fonts,
  });
/** The default console face is the publication serif; swap by name to reverse. */
export const consoleDark = consoleDarkSerif;

export const FIXTURE_AXES = {
  parchment: PARCHMENT_AXES,
  substrate: SUBSTRATE_AXES,
  print: PRINT_AXES,
  "console-dark": CONSOLE_DARK_AXES,
} as const;

/** Every named fixture register, one call each (the artifact generation map). */
export const FIXTURE_REGISTERS: Record<string, () => Register> = {
  parchment,
  substrate,
  print,
  "console-dark": consoleDark,
  "console-dark-serif": consoleDarkSerif,
  "console-dark-sans": consoleDarkSans,
};
